name: develop

on:
  push:
    branches-ignore:
      - master

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

env:      
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TERM: xterm

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Linux Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsfml-dev x11-apps x11-xserver-utils

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        cache: 'sbt'
        distribution: 'temurin'
        java-version: '17'

    - name: Check lint
      run: |
        find . -name "*.cpp" -exec clang-format --dry-run --Werror {} +
        sbt -v scalafmtCheckAll

    - name: Build
      run: sbt -v 'set nativeLTO := "none"; set nativeMode := "debug"; compile'

    - name: Tests
      run: |
        sbt -v 'set nativeLTO := "none"; set nativeMode := "debug"; test'
        make -C src/test/cxx
        ./launch_tests.sh
