name: develop

on:
  push:
    branches-ignore:
      - master

concurrency:
  group: ci-develop-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TERM: xterm

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Linux Dependencies
      run: sudo apt-get install libsfml-dev x11-apps x11-xserver-utils xvfb

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        cache: 'sbt'
        distribution: 'temurin'
        java-version: '17'

    - name: Check lint
      run: sbt -v scalafmtCheckAll

    - name: Build
      run: sbt -v 'set sfml / nativeLTO := "none"; set sfml / nativeMode := "debug"; sfml / compile'

    - name: Tests
      run: |
        sbt -v 'set tests / nativeLTO := "none"; set tests / nativeMode := "debug"; tests / nativeLink'
        make -C tests
        ./tests/launch.sh
