name: develop

on:
  push:
    branches-ignore:
      - master

concurrency:
  group: ci-develop-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Linux Dependencies
      run: sudo apt-get install libsfml-dev x11-apps xvfb

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Coursier cache
      uses: coursier/cache-action@v6

    - name: Check lint
      run: sbt -v scalafmtCheckAll

    - name: Build
      run: sbt -v 'set sfml / nativeLTO := "none"; set sfml / nativeMode := "debug"; sfml / compile'

    - name: Tests
      run: |
        sbt -v 'set tests / nativeLTO := "none"; set tests / nativeMode := "debug"; tests / nativeLink'
        make -C tests
        ./tests/launch.sh

    - name: Cleanup before cache
      shell: bash
      run: |
        rm -rf "$HOME/.ivy2/local" || true
        find $HOME/Library/Caches/Coursier/v1 -name "ivydata-*.properties" -delete || true
        find $HOME/.ivy2/cache                -name "ivydata-*.properties" -delete || true
        find $HOME/.cache/coursier/v1         -name "ivydata-*.properties" -delete || true
        find $HOME/.sbt                       -name "*.lock"               -delete || true
