name: Publish

on:
  push:
    tags:
      - "v*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Linux Dependencies
      run: sudo apt-get update && sudo apt-get install libcsfml-dev

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Coursier cache
      uses: coursier/cache-action@v6

    - name: Publish
      run: sbt publish

    - name: Cleanup before cache
      shell: bash
      run: |
        rm -rf "$HOME/.ivy2/local" || true
        find $HOME/Library/Caches/Coursier/v1 -name "ivydata-*.properties" -delete || true
        find $HOME/.ivy2/cache                -name "ivydata-*.properties" -delete || true
        find $HOME/.cache/coursier/v1         -name "ivydata-*.properties" -delete || true
        find $HOME/.sbt                       -name "*.lock"               -delete || true
